### ISSUE TITLE
Map Crash when change class 

### ISSUE THREAD

**Issue by potynobg** [liodali/osm_flutter#184]
I/flutter (31309): GeoPoint{latitude: 45.64986666666667 , longitude: 9.609708333333334}
I/flutter (31309): GeoPoint{latitude: 45.64986666666667 , longitude: 9.609708333333334}
I/flutter (31309): GeoPoint{latitude: 45.64986666666667 , longitude: 9.609708333333334}
I/flutter (31309): GeoPoint{latitude: 45.64986666666667 , longitude: 9.609708333333334}
I/flutter (31309): GeoPoint{latitude: 45.64986666666667 , longitude: 9.609708333333334}
I/ViewRootImpl@4ea5f28[MainActivity](31309): ViewPostIme pointer 0
I/ViewRootImpl@4ea5f28[MainActivity](31309): ViewPostIme pointer 1
I/Dialog  (31309): mIsSamsungBasicInteraction = false, isMetaDataInActivity = false
I/OsmDroid(31309): Using tile source: Mapnik
I/OsmDroid(31309): Tile cache increased from 0 to 9
E/osm     (31309): osm flutter plugin create
E/osm     (31309): osm flutter plugin start
E/osm     (31309): osm flutter plugin resume
I/DecorView(31309): [INFO] isPopOver=false, config=false
I/DecorView(31309): updateCaptionType >> DecorView@3c7bed8[], isFloating=false, isApplication=false, hasWindowDecorCaption=false, hasWindowControllerCallback=false
D/DecorView(31309): setCaptionType = 0, this = DecorView@3c7bed8[]
D/NativeCustomFrequencyManager(31309): [NativeCFMS] BpCustomFrequencyManager::BpCustomFrequencyManager()
D/InputTransport(31309): Input channel constructed: 'da05fe0', fd=124
I/ViewRootImpl@ae324a2[MainActivity](31309): setView = com.android.internal.policy.DecorView@3c7bed8 TM=true
I/SurfaceControl(31309): assignNativeObject: nativeObject = 0 Surface(name=null)/@0x19390f0 / android.view.SurfaceControl.readFromParcel:1117 android.view.IWindowSession$Stub$Proxy.relayout:1820 android.view.ViewRootImpl.relayoutWindow:9005 android.view.ViewRootImpl.performTraversals:3360 android.view.ViewRootImpl.doTraversal:2618 android.view.ViewRootImpl$TraversalRunnable.run:9971 android.view.Choreographer$CallbackRecord.run:1010 android.view.Choreographer.doCallbacks:809 android.view.Choreographer.doFrame:744 android.view.Choreographer$FrameDisplayEventReceiver.run:995 
I/ViewRootImpl@ae324a2[MainActivity](31309): Relayout returned: old=(0,0,1080,1859) new=(0,0,1080,1859) req=(1080,1859)0 dur=15 res=0x7 s={true -5476376641944449024} ch=true fn=-1
I/OsmDroid(31309): Tile cache increased from 9 to 12
D/OpenGLRenderer(31309): GPIS:: SetUp Pid : 31309    Tid : 5546
I/flutter (31309): GeoPoint{latitude: 45.64986666666667 , longitude: 9.609708333333334}
I/flutter (31309): GeoPoint{latitude: 45.64986666666667 , longitude: 9.609708333333334}
I/Dialog  (31309): mIsSamsungBasicInteraction = false, isMetaDataInActivity = false
I/OsmDroid(31309): Using tile source: Mapnik
I/OsmDroid(31309): Tile cache increased from 0 to 9
E/osm     (31309): osm flutter plugin create
E/osm     (31309): osm flutter plugin start
E/osm     (31309): osm flutter plugin resume
I/DecorView(31309): [INFO] isPopOver=false, config=false
I/DecorView(31309): updateCaptionType >> DecorView@d88ad11[], isFloating=false, isApplication=false, hasWindowDecorCaption=false, hasWindowControllerCallback=false
D/DecorView(31309): setCaptionType = 0, this = DecorView@d88ad11[]
D/NativeCustomFrequencyManager(31309): [NativeCFMS] BpCustomFrequencyManager::BpCustomFrequencyManager()
D/InputTransport(31309): Input channel constructed: 'e20bdd0', fd=154
I/ViewRootImpl@c7c3913[MainActivity](31309): setView = com.android.internal.policy.DecorView@d88ad11 TM=true
I/ViewRootImpl@ae324a2[MainActivity](31309): dispatchDetachedFromWindow
I/SurfaceControl(31309): nativeRelease nativeObject s[-5476376644262214720]
I/SurfaceControl(31309): nativeRelease nativeObject e[-5476376644262214720]
D/InputTransport(31309): Input channel destroyed: 'da05fe0', fd=124
E/map center(31309): {lon=9.609375, lat=45.650254088774695}
E/AndroidRuntime(31309): FATAL EXCEPTION: main
E/AndroidRuntime(31309): Process: it.nexid.justintrain, PID: 31309
E/AndroidRuntime(31309): java.lang.NullPointerException: Attempt to invoke virtual method 'org.osmdroid.views.MapViewRepository org.osmdroid.views.MapView.getRepository()' on a null object reference
E/AndroidRuntime(31309): 	at org.osmdroid.views.overlay.infowindow.InfoWindow.<init>(InfoWindow.java:53)
E/AndroidRuntime(31309): 	at org.osmdroid.views.overlay.infowindow.BasicInfoWindow.<init>(BasicInfoWindow.java:54)
E/AndroidRuntime(31309): 	at org.osmdroid.views.overlay.infowindow.MarkerInfoWindow.<init>(MarkerInfoWindow.java:41)
E/AndroidRuntime(31309): 	at org.osmdroid.views.MapViewRepository.getDefaultMarkerInfoWindow(MapViewRepository.java:55)
E/AndroidRuntime(31309): 	at org.osmdroid.views.overlay.Marker.<init>(Marker.java:116)
E/AndroidRuntime(31309): 	at org.osmdroid.views.overlay.Marker.<init>(Marker.java:93)
E/AndroidRuntime(31309): 	at hamza.dali.flutter_osm_plugin.FlutterMarker.<init>(FlutterMaker.kt:22)
E/AndroidRuntime(31309): 	at hamza.dali.flutter_osm_plugin.FlutterMarker.<init>(FlutterMaker.kt:42)
E/AndroidRuntime(31309): 	at hamza.dali.flutter_osm_plugin.FlutterOsmView.showStaticPosition(FlutterOsmView.kt:1532)
E/AndroidRuntime(31309): 	at hamza.dali.flutter_osm_plugin.FlutterOsmView.access$showStaticPosition(FlutterOsmView.kt:87)
E/AndroidRuntime(31309): 	at hamza.dali.flutter_osm_plugin.FlutterOsmView$setCacheMap$2$1$1.invokeSuspend(FlutterOsmView.kt:479)
E/AndroidRuntime(31309): 	at hamza.dali.flutter_osm_plugin.FlutterOsmView$setCacheMap$2$1$1.invoke(Unknown Source:8)
E/AndroidRuntime(31309): 	at hamza.dali.flutter_osm_plugin.FlutterOsmView$setCacheMap$2$1$1.invoke(Unknown Source:4)
E/AndroidRuntime(31309): 	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
E/AndroidRuntime(31309): 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:165)
E/AndroidRuntime(31309): 	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
E/AndroidRuntime(31309): 	at hamza.dali.flutter_osm_plugin.FlutterOsmView$setCacheMap$2.invokeSuspend(FlutterOsmView.kt:478)
E/AndroidRuntime(31309): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
E/AndroidRuntime(31309): 	at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:377)
E/AndroidRuntime(31309): 	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:30)
E/AndroidRuntime(31309): 	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:25)
E/AndroidRuntime(31309): 	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:110)
E/AndroidRuntime(31309): 	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
E/AndroidRuntime(31309): 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
E/AndroidRuntime(31309): 	at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1)
E/AndroidRuntime(31309): 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
E/AndroidRuntime(31309): 	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:1)
E/AndroidRuntime(31309): 	at hamza.dali.flutter_osm_plugin.FlutterOsmView.setCacheMap(FlutterOsmView.kt:470)
E/AndroidRuntime(31309): 	at hamza.dali.flutter_osm_plugin.FlutterOsmView.onMethodCall(FlutterOsmView.kt:268)
E/AndroidRuntime(31309): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/AndroidRuntime(31309): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:84)
E/AndroidRuntime(31309): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:865)
E/AndroidRuntime(31309): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/AndroidRuntime(31309): 	at android.os.MessageQueue.next(MessageQueue.java:335)
E/AndroidRuntime(31309): 	at android.os.Looper.loop(Looper.java:206)
E/AndroidRuntime(31309): 	at android.app.ActivityThread.main(ActivityThread.java:8595)
E/AndroidRuntime(31309): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(31309): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
E/AndroidRuntime(31309): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
I/Process (31309): Sending signal. PID: 31309 SIG: 9

**Comment by potynobg** [comment]
Code used is this 

`import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter/widgets.dart';
import 'package:flutter_osm_plugin/flutter_osm_plugin.dart';
import 'package:justintrainflutter/Oggetti/barrainalto.dart';
import 'package:justintrainflutter/Oggetti/strutture.dart';
import 'package:justintrainflutter/config/appvariablesingleton.dart';
import 'package:justintrainflutter/pages/schedastazione.dart';

class Principale extends StatefulWidget {
  const Principale({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  _PrincipaleState createState() => _PrincipaleState();
}

class _PrincipaleState extends State<Principale> {
  late GlobalKey<ScaffoldState> scaffoldKey;
  final GlobalKey principaleKey = GlobalKey();
  List<Stazioni> stazioni = [];
  late List<StaticPositionGeoPoint> geoPointsStatici = [];
  late ValueNotifier<double> extentHeight;
  double minAlpha = 0.20;
  var sheetIndexNotifier = ValueNotifier(0);
  ValueNotifier<double> maxAlphaNotifier = ValueNotifier(0.65);
  late ValueNotifier<double> diffAlphaNotifier =
  ValueNotifier(maxAlphaNotifier.value - minAlpha);
  late double maxHeight, minHeight;
  ValueNotifier<bool> advPickerNotifierActivation = ValueNotifier(false);
  ValueNotifier<bool> trackingNotifier = ValueNotifier(false);
  ValueNotifier<bool> zoomNotifierActivation = ValueNotifier(false);
  ValueNotifier<bool> visibilityZoomNotifierActivation = ValueNotifier(false);
  final List<GeoPoint> geoPoints = [];

  @override
  void initState() {

    super.initState();
    scaffoldKey = GlobalKey<ScaffoldState>();

    for(var singola in AppVariableSingleton.shared.tuttelestazioni) {
      GeoPoint nuovo = GeoPoint(latitude: singola.latitudine, longitude: singola.longitudine);
      geoPoints.add(nuovo);
    }

  }


  @override
  void dispose() {
    //controller.listenerMapIsReady.removeListener(mapIsInitialized);
    super.dispose();
  }

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    maxHeight = MediaQuery.of(context).size.height * maxAlphaNotifier.value;
    minHeight = MediaQuery.of(context).size.height * minAlpha;
    extentHeight = ValueNotifier(maxAlphaNotifier.value);
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: const BarraInAlto(),
      key: scaffoldKey,
      resizeToAvoidBottomInset: false,
      body: SimpleOSM(geoPoints: geoPoints,),
    );
  }

  bool caricalestazioni() {
    return true;
  }

}

class CustomScroll extends ScrollBehavior {
  @override
  Widget buildOverscrollIndicator(
      BuildContext context, Widget child, ScrollableDetails details) {
    return child;
  }

  @override
  Widget buildScrollbar(
      BuildContext context, Widget child, ScrollableDetails details) {
    return child;
  }
}

class SimpleOSM extends StatefulWidget {

  List<GeoPoint> geoPoints = [];

  SimpleOSM({Key? key, required this.geoPoints}) : super(key: key);

  @override
  State<StatefulWidget> createState() => SimpleOSMState();
}

class SimpleOSMState extends State<SimpleOSM> with AutomaticKeepAliveClientMixin {

  MapController controller = MapController(
    initMapWithUserPosition: true,
    initPosition: GeoPoint(latitude: 45.6470495, longitude: 9.5636417)
  );

  @override
  void initState() {
    controller.listenerMapIsReady.addListener(mapIsInitialized);
    super.initState();
  }

  @override
  void dispose() {
    controller.listenerMapIsReady.removeListener(mapIsInitialized);
    controller.dispose();
    super.dispose();
  }

  @override
  @mustCallSuper
  Widget build(BuildContext context) {
    super.build(context);
    return OSMFlutter(
      controller: controller,
      mapIsLoading: Center(
        child: Column(
          mainAxisSize: MainAxisSize.min,
          mainAxisAlignment: MainAxisAlignment.center,
          crossAxisAlignment: CrossAxisAlignment.center,
          children: const [
            CircularProgressIndicator(),
            Text("Sto caricando la mappa..")
          ],
        ),
      ),
      showZoomController: true,
      trackMyPosition: true,
      // showZoomController: true,
      initZoom: 10,
      minZoomLevel: 2,
      maxZoomLevel: 18,
      stepZoom: 1.0,
      userLocationMarker: UserLocationMaker(
        personMarker: MarkerIcon(
          icon: const Icon(
            Icons.emoji_people,
            color: Colors.red,
            size: 96,
          ),
        ),
        directionArrowMarker: MarkerIcon(
          icon: const Icon(
            Icons.double_arrow,
            size: 96,
          ),
        ),
      ),
      showContributorBadgeForOSM: true,
      //trackMyPosition: trackingNotifier.value,
      showDefaultInfoWindow: false,
      onLocationChanged: (myLocation) {
        print(myLocation);
      },
      onGeoPointClicked: (geoPoint) async {
        Stazioni lastazione = lastazionedacoordinate(geoPoint.latitude, geoPoint.longitude);
        asyncTrenoDialog(context, lastazione);
      },
      markerOption: MarkerOption(
        defaultMarker: MarkerIcon(
          icon: const Icon(
            Icons.home,
            color: Colors.orange,
            size: 96,
          ),
        ),
        advancedPickerMarker: MarkerIcon(
          icon: const Icon(
            Icons.location_searching,
            color: Colors.green,
            size: 96,
          ),
        ),
      ),
    );
  }


  @override
  bool get wantKeepAlive => true;

  void mapIsInitialized() async {
    if (controller.listenerMapIsReady.value) {

      setState(() {

        controller.enableTracking();

        controller.listenerMapSingleTapping.addListener(() {
          if (controller.listenerMapSingleTapping.value != null) {
            print(controller.listenerMapSingleTapping.value);
          }
        });


      });


      // Future.delayed(Duration(seconds: 5), () async {
      //   await controller.zoomIn();
      // });
      Future.delayed(const Duration(seconds: 1), () async {
        await controller.setZoom(zoomLevel: 12);
        await controller.setMarkerOfStaticPoint(
          id: "Treno",
          markerIcon: MarkerIcon(
            icon: const Icon(
              Icons.train,
              color: Colors.redAccent,
              size: 96,
            ),
          ),
        );
        await controller.setStaticPosition(
          widget.geoPoints,
          "Treno",
        );
      });
    }
  }

  @override
  void didUpdateWidget(covariant SimpleOSM oldWidget) {
    if (oldWidget != widget) {
      controller = MapController(
        initMapWithUserPosition: false,
        initPosition: GeoPoint(
          latitude: 45.6499755,
          longitude: 9.6096992,
        ),
      );

      controller.listenerMapSingleTapping.addListener(() {
        if (controller.listenerMapSingleTapping.value != null) {
          print(controller.listenerMapSingleTapping.value);
        }
      });

      controller.listenerMapIsReady.addListener(mapIsInitialized);
    }
    super.didUpdateWidget(oldWidget);
  }

  /// Mostra la dialog con i dati della stazione
  Future asyncTrenoDialog(BuildContext context, Stazioni stazione) async {
    return showDialog<bool>(
      context: context,
      barrierDismissible: true,
      builder: (BuildContext context) {
        return AlertDialog(
            backgroundColor: Colors.yellow,
            title: Row(children: [
              Container(
                margin: const EdgeInsets.fromLTRB(10, 0, 10, 0),
                child: Image.asset(
                  "assets/images/rail.png",
                  width: 50,
                  height: 50,
                  fit: BoxFit.contain,
                  color: Colors.black,
                ),
              ),
              Expanded(
                child: Text("Stazione di ${stazione.stazione}",
                    style: const TextStyle(fontFamily: 'Dotmatrix',
                        fontSize: 18,
                        fontWeight: FontWeight.bold, color: Colors.black)),
              )]),
            content: const Text("Premi su arrivi o partenze per vedere i treni",
                style: TextStyle(fontFamily: 'Dotmatrix',
                    fontSize: 16,
                    fontWeight: FontWeight.normal, color: Colors.black)),
            actions: [
              TextButton(
                style: ButtonStyle(
                    backgroundColor:
                    MaterialStateProperty.all(Colors.red)),
                child: const Text("Arrivi",
                    style: TextStyle(fontFamily: 'Dotmatrix',
                        fontSize: 16,
                        fontWeight: FontWeight.bold, color: Colors.black)),
                onPressed: () {
                  Navigator.push(
                    context,
                    MaterialPageRoute(
                      builder: (context) => SchedaStazione(ap: "1", stazione: stazione.codice),
                    ),
                  );
                },
              ),
              TextButton(
                style: ButtonStyle(
                    backgroundColor:
                    MaterialStateProperty.all(Colors.green)),
                child: const Text("Partenze",
                    style: TextStyle(fontFamily: 'Dotmatrix',
                        fontSize: 16,
                        fontWeight: FontWeight.bold, color: Colors.black)),
                onPressed: () {
                  Navigator.push(
                    context,
                    MaterialPageRoute(
                      builder: (context) => SchedaStazione(ap: "2", stazione: stazione.codice),
                    ),
                  );
                },
              )
            ]);
          },
        );
  }

  Stazioni lastazionedacoordinate(double latitudine, double longitudine) {
    Stazioni ritorno = Stazioni("000", "000", "NESSUNA", 0.0, 0.0, "NESSUNA", "NESSUNA", "NO", false);
    for(var singola in AppVariableSingleton.shared.tuttelestazioni) {
      if(singola.latitudine == latitudine && singola.longitudine == longitudine) {
        return singola;
      }
    }
    return ritorno;
  }

  TextStyle stiletesto() {
    return const TextStyle(fontFamily: 'Dotmatrix',
        fontSize: 16,
        fontWeight: FontWeight.normal,
        color: Colors.black);
  }

}`

**Comment by liodali** [comment]
remove stetState in `mapIsInitialized` 
and can you describe that happen exactly

**Comment by potynobg** [comment]
even without 'stetState' absolutely nothing changes. The crash remains

**Comment by liodali** [comment]
can you describe scenario that cause the problem

**Comment by liodali** [comment]
did you mean that map crash when you try to open new page or something like that !

**Comment by potynobg** [comment]
the map is on the main page of the application.
the version is v0.25.0-rc.4.
When I run the application for the first time (app deleted and reinstalled via adb port) the map is not visible.
At the second restart, always in debug mode, the map is shown but without the right coordinates (no Milan but ocean).

after a long time the position is updated based on the GPS / GLONASS and finally I see the map positioned at the right point.
When I exit the page and return to it I get the crash

version 0.23 is not compile. Gradle is not collaborative.
Despite having deleted everything (formatted computer, reinstalled MAC OS, reinstalled Android Studio, made new project with flutter.
pasted only the source code into a new app.
nothing works nothing.
Version v0.25.0-rc.4 works but if the app goes in the background or you change view nothing to do.

```
my build gradle level project

buildscript {
    ext.kotlin_version = '1.5.31'
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:7.0.3'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.3.10'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

```

build.gradle at level app

```
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"
apply plugin: 'com.google.gms.google-services'


android {
    compileSdkVersion 31

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "it.nexid.justintrain"
        minSdkVersion 22
        targetSdkVersion 31
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        multiDexEnabled = true
    }

    signingConfigs {

        release {
            storeFile file('keystore')
            storePassword "nexid2021"
            keyAlias = "key"
            keyPassword "nexid2021"
            v1SigningEnabled true
            v2SigningEnabled true
        }
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.release
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation("androidx.multidex:multidex:2.0.1")
    implementation 'com.google.android.material:material:1.4.0'
    implementation platform('com.google.firebase:firebase-bom:28.4.0')
    implementation 'com.google.firebase:firebase-analytics-ktx'
}
```

Android Manifest

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    package="it.nexid.justintrain">
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>
    <uses-permission android:name="android.permission.ACCESS_BACKGROUND_LOCATION" />
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"  />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />

   <application
        android:label="justintrain"
        android:icon="@mipmap/ic_launcher">
        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize"
            android:usesCleartextTraffic="true"
            android:exported = "true"
            tools:targetApi="m">
            <!-- Specifies an Android theme to apply to this Activity as soon as
                 the Android process has started. This theme is visible to the user
                 while the Flutter UI initializes. After that, this theme continues
                 to determine the Window background behind the Flutter UI. -->
            <meta-data
              android:name="io.flutter.embedding.android.NormalTheme"
              android:resource="@style/NormalTheme"
              />
            <!-- Displays an Android View that continues showing the launch screen
                 Drawable until Flutter paints its first frame, then this splash
                 screen fades out. A splash screen is useful to avoid any visual
                 gap between the end of Android's launch screen and the painting of
                 Flutter's first frame. -->
            <meta-data
              android:name="io.flutter.embedding.android.SplashScreenDrawable"
              android:resource="@drawable/launch_background"
              />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
        <!-- Don't delete the meta-data below.
             This is used by the Flutter tool to generate GeneratedPluginRegistrant.java -->
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
    </application>
</manifest>

```

**Comment by potynobg** [comment]
Hoi,
Mohamed, 

You are really smart;
with the RC 5 you have solved most of the problems very quickly. Many compliments. Excellent.
Just a small thing, the swipe area (up, down, right, left) seems to me really small, you have to act for less than 5 millimeters, it can be extended to two / three centimeters, if one doesn't know, the map does not move it anymore.
TNK ... remember U're very smart programmer

**Comment by liodali** [comment]
can you explain more about the problem of swipe ? 
what did you mean by small

**Comment by potynobg** [comment]
Swipe Left : not work 
Swipe Right : not work 
Swipe Up, Down : work but swipe area is very reduced, U can swipe in 5 - 10 millimeters screen for move map if U swipe for 4-5 centimeter not work
