### ISSUE TITLE
OSM flutter app keeps exiting

### ISSUE THREAD

**Issue by jesussmile** [liodali/osm_flutter#189]
Hi Hamza! After the recent updates on the plugin the App will exit with the following errors, I don't understand why this error is happening, please take a look, worked fine with older plugins. Right now I am on `0.26.0-rc.2` If you want I can share my project with you or try to create a smaller one to show this error. The problem is the app will exit after this error. I think it has to do with markers being created before map is reloaded or sth?

```

I/flutter (18097): xxx GeoPoint{latitude: 27.7021583 , longitude: 85.347035}
I/flutter (18097): xxxb GeoPoint{latitude: 27.6718111 , longitude: 85.4264284}
D/BONUSPACK(18097): OSRMRoadManager.getRoads:https://routing.openstreetmap.de/routed-car/route/v1/driving/85.3470350000,27.7021583000;85.4264284000,27.6718111000?alternatives=false&overview=full&steps=true
I/flutter (18097): didchange Dependencies test
I/OsmDroid(18097): Using tile source: Mapnik
I/OsmDroid(18097): Tile cache increased from 0 to 9
E/osm     (18097): osm flutter plugin create
E/osm     (18097): osm flutter plugin start
E/osm     (18097): osm flutter plugin resume
E/map center(18097): {lon=-122.08413947712292, lat=37.42201005029876}
I/flutter (18097): didchange Dependencies test
I/OsmDroid(18097): Using tile source: Mapnik

I/OsmDroid(18097): Tile cache increased from 0 to 9
E/osm     (18097): osm flutter plugin create
E/osm     (18097): osm flutter plugin start
E/osm     (18097): osm flutter plugin resume
W/System  (18097): A resource failed to call release.
D/BONUSPACK(18097): OSRMRoadManager.getRoads - finished
E/AndroidRuntime(18097): FATAL EXCEPTION: DefaultDispatcher-worker-2
E/AndroidRuntime(18097): Process: com.example.geo_rider, PID: 18097
E/AndroidRuntime(18097): java.lang.NullPointerException: Attempt to invoke virtual method 'org.osmdroid.views.MapViewRepository org.osmdroid.views.MapView.getRepository()' on a null object reference
E/AndroidRuntime(18097): 	at org.osmdroid.views.overlay.infowindow.InfoWindow.<init>(InfoWindow.java:53)
E/AndroidRuntime(18097): 	at org.osmdroid.views.overlay.infowindow.BasicInfoWindow.<init>(BasicInfoWindow.java:54)
E/AndroidRuntime(18097): 	at org.osmdroid.views.overlay.infowindow.MarkerInfoWindow.<init>(MarkerInfoWindow.java:41)
E/AndroidRuntime(18097): 	at org.osmdroid.views.MapViewRepository.getDefaultMarkerInfoWindow(MapViewRepository.java:55)
E/AndroidRuntime(18097): 	at org.osmdroid.views.overlay.Marker.<init>(Marker.java:116)
E/AndroidRuntime(18097): 	at org.osmdroid.views.overlay.Marker.<init>(Marker.java:93)

E/AndroidRuntime(18097): 	at hamza.dali.flutter_osm_plugin.FlutterMarker.<init>(FlutterMaker.kt:22)
E/AndroidRuntime(18097): 	at hamza.dali.flutter_osm_plugin.FlutterMarker.<init>(FlutterMaker.kt:55)
E/AndroidRuntime(18097): 	at hamza.dali.flutter_osm_plugin.FlutterRoadMarker.<init>(FlutterRoadMarker.kt:10)
E/AndroidRuntime(18097): 	at hamza.dali.flutter_osm_plugin.FlutterRoad.initStartEndPoints(FlutterRoad.kt:37)
E/AndroidRuntime(18097): 	at hamza.dali.flutter_osm_plugin.FlutterRoad.setRoad(FlutterRoad.kt:23)
E/AndroidRuntime(18097): 	at hamza.dali.flutter_osm_plugin.FlutterOsmView.createRoad(FlutterOsmView.kt:1349)
E/AndroidRuntime(18097): 	at hamza.dali.flutter_osm_plugin.FlutterOsmView.access$createRoad(FlutterOsmView.kt:87)
E/AndroidRuntime(18097): 	at hamza.dali.flutter_osm_plugin.FlutterOsmView$drawRoad$2$1$2.invokeSuspend(FlutterOsmView.kt:1294)
E/AndroidRuntime(18097): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
E/AndroidRuntime(18097): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
E/AndroidRuntime(18097): 	at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime(18097): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(18097): 	at android.os.Looper.loop(Looper.java:223)
E/AndroidRuntime(18097): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/AndroidRuntime(18097): 	at java.lang.reflect.Method.invoke(Native Method)

E/AndroidRuntime(18097): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/AndroidRuntime(18097): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
I/Process (18097): Sending signal. PID: 18097 SIG: 9
Lost connection to device.

```
This is my mainactivity where I have a function `showMap` 
```ruby
 Future showMap(bool checkValue) async {
    setState(() {
    
      locationPick = false;
      rideRequest = true;
      floatingActionButton = false;

      // print("****TestFunction under testFunction $checkValue");
    });
    try {
      await osmController.removeLastRoad();

      GeoPoint pointA = initPosition;
      print("xxx $pointA");

      GeoPoint pointB =
          Provider.of<AppData>(context, listen: false).dropOffLatLng;
      print("xxxb $pointB");
      RoadInfo roadInformation = await osmController.drawRoad(pointA, pointB,
          //interestPoints: [pointM1, pointM2],
          roadOption: RoadOption(
              roadWidth: 10, roadColor: Colors.red, showMarkerOfPOI: true));
      String duration =
          "duration: ${Duration(seconds: roadInformation.duration.toInt()).inMinutes} minutes ";

      setState(() {
        price = (roadInformation.distance * 39 + 50).toStringAsFixed(2);
        distance = "${roadInformation.distance.toStringAsFixed(2)} Km ";
      });

      getMidPointLatLong(pointA, pointB);

      //String totalPrice = " Price $price";

      print(duration);
      print(distance);
      // ScaffoldMessenger.of(context).showSnackBar(SnackBar(
      //     duration: Duration(seconds: 5),
      //     content: Text(
      //       duration + distance + price,
      //     )));
    } on RoadException catch (e) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text(
            "${e.errorMessage()}",
          ),
        ),
      );
    }

///
 @override
  Widget build(BuildContext context) {
      ///
GestureDetector(
                          onTap:
                           
                              () async {
                          
                            await Navigator.push(
                                context,
                                MaterialPageRoute(
                                    builder: (context) => SearchScreen(
                                        showMapFunction: showMap)));
                          },}
```
This is the searchscreen
```ruby
import 'package:flutter/material.dart';
//import 'package:flutter_keyboard_visibility/flutter_keyboard_visibility.dart';
import 'package:flutter_osm_plugin/flutter_osm_plugin.dart';
import 'package:flutter_typeahead/flutter_typeahead.dart';
import 'package:provider/provider.dart';
//import 'package:rider/AllScreens/mainscreen.dart';
//import 'package:rider/AllScreens/photonAPI.dart';
import 'package:geo_rider/DataHandler/appData.dart';

import 'dart:async';

class SearchScreen extends StatefulWidget {
  final Function showMapFunction;
  // final String ;

  const SearchScreen({this.showMapFunction}); //,this.String});

  @override
  _SearchScreenState createState() => _SearchScreenState();
}

class _SearchScreenState extends State<SearchScreen> {
  TextEditingController pickUpTextEditingController = TextEditingController();
  TextEditingController dropOffTextEditingController = TextEditingController();

  //final AppData appdata;

  @override
  void initState() {
    super.initState();
  }

  @override
  @mustCallSuper
  Widget build(BuildContext context) {
    String placeAddress =
        Provider.of<AppData>(context).pickUpLocation.placeName ?? "";
    pickUpTextEditingController.text = placeAddress;

    return Scaffold(
      resizeToAvoidBottomInset: false,
      body: Stack(
        children: [
          Container(
            height: 250.0,
            decoration: BoxDecoration(
              color: Colors.white,
              boxShadow: [
                BoxShadow(
                  color: Colors.black,
                  blurRadius: 6.0,
                  spreadRadius: 0.5,
                  offset: Offset(0.7, 0.7),
                )
              ],
            ),
            child: Padding(
              padding: EdgeInsets.only(
                  left: 25.0, top: 30.0, right: 25.0, bottom: 20.0),
              child: Column(
                children: [
                  SizedBox(height: 5.0),
                  Stack(
                    children: [
                      GestureDetector(
                          onTap: () async {
                            FocusScopeNode currentFocus =
                                FocusScope.of(context);
                            if (!currentFocus.hasPrimaryFocus) {
                              currentFocus.unfocus();
                            }
                            Navigator.pop(
                                //send back data
                                context,
                                widget.showMapFunction(false));
                            // print("object");
                            //);
                          },
                          child: Icon(Icons.arrow_back)),
                      Center(
                        child: Text(
                          "Choose your drop off ",
                          style: TextStyle(
                              fontSize: 18.0, fontFamily: "Brand-Bold"),
                        ),
                      )
                    ],
                  ),
                  SizedBox(height: 16.0),
                  Row(
                    children: [
                      Image.asset("images/images/pickicon.png",
                          height: 16.0, width: 16.0),
                      SizedBox(width: 18.0),
                      Expanded(
                          child: Container(
                        decoration: BoxDecoration(
                          color: Colors.grey[400],
                          borderRadius: BorderRadius.circular(5.0),
                        ),
                        child: Padding(
                          padding: EdgeInsets.all(3.0),
                          child: TextField(
                            controller: pickUpTextEditingController,
                            decoration: InputDecoration(
                              hintText: "PickUp Location",
                              fillColor: Colors.grey[400],
                              filled: true,
                              border: InputBorder.none,
                              isDense: true,
                              contentPadding: EdgeInsets.only(
                                  left: 11.0, top: 8.0, bottom: 8.0),
                            ),
                          ),
                        ),
                      ))
                    ],
                  ),
                  SizedBox(height: 10.0),
                  Row(
                    children: [
                      Image.asset("images/images/desticon.png",
                          height: 16.0, width: 16.0),
                      SizedBox(width: 18.0),
                      Expanded(
                        child: Container(
                          decoration: BoxDecoration(
                            color: Colors.grey[400],
                            borderRadius: BorderRadius.circular(5.0),
                          ),
                          child: Padding(
                            padding: EdgeInsets.all(3.0),
                            child: TypeAheadField(
                              textFieldConfiguration: TextFieldConfiguration(
                                autofocus: false,
                                maxLines: 1,
                                controller: dropOffTextEditingController,
                                decoration: InputDecoration(
                                  contentPadding: EdgeInsets.all(3),
                                  hintText: "Pick two points",
                                  labelStyle: TextStyle(color: Colors.black),
                                  focusedBorder: OutlineInputBorder(
                                    borderSide: BorderSide(
                                        width: 1.3, color: Colors.black),
                                  ),
                                  border: OutlineInputBorder(
                                    borderSide: BorderSide(width: 0.8),
                                  ),
                                ),
                              ),
                              suggestionsCallback: (pattern) async {
                                if (pattern.isNotEmpty)
                                  return await addressSuggestion(pattern);
                                return Future.value();
                              },
                              suggestionsBoxController:
                                  SuggestionsBoxController(),
                              itemBuilder: (context, suggestion) {
                                return ListTile(
                                  leading: Icon(Icons.location_on),
                                  title: Text(
                                      (suggestion as SearchInfo).address.name),
                                  subtitle: Text((suggestion).address.country),
                                );
                              },
                              onSuggestionSelected: (suggestion) {
                                print("xxx $suggestion");

                                dropOffTextEditingController.text =
                                    (suggestion as SearchInfo).address.name;
                                Provider.of<AppData>(context, listen: false)
                                    .updateDropOffLocationAddress(
                                        dropOffTextEditingController.text);
                                //get the coordinates here
                                GeoPoint dropOffPoint =
                                    (suggestion as SearchInfo).point;
                                print("Coordinates :$dropOffPoint");
                                Provider.of<AppData>(context, listen: false)
                                    .updateDropOffGeoPoint(dropOffPoint);

                                // Navigator.pop(
                                //     context, widget.showMapFunction(false));
                              },
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ],
              ),
            ),
          ),
        ],
      ),
    );
  }
}

**Comment by liodali** [comment]
remove setState in the method showMap
both of the setState and  replace distance and price type with valueNotifier<double> 
if you show the price in the widget use ValueListenableBuilder to get last value without need to rebuild all the widget 
for now setState in android will cause lot of crash try to avoid using it
alos you dont need to make nested setState

**Comment by jesussmile** [comment]
Ok got it now! I finally understand it now the issue with `setState` was causing problems with other parts of the code as well, I replaced all of it with `Consumer` and `Provider` package . Seems to work fine now.
