### ISSUE TITLE
What causes the map to black out?

### ISSUE THREAD

**Issue by mor7348** [liodali/osm_flutter#221]
My program blacked out the map, so I tried it with '/example/lib/src/home/home_example.dart' and it looks the same.
Do you know the cause?

![Simulator Screen Shot - iPhone 11 Pro Max - 2022-02-01 at 11 50 43](https://user-images.githubusercontent.com/38882637/151906952-0fbdba75-e1ac-445d-95ee-ad96cc96f9df.png)

**Comment by liodali** [comment]
that problem in rendering engine in iOS 
i will check it

**Comment by liodali** [comment]
are you still facing the same problem?
because i tested and i didn't face black screen

**Comment by mor7348** [comment]
Sorry for the late reply.

The map blackout is still going on.

I got the following error and fixed it manually.

~~ / development / flutter / .pub-cache / hosted / pub.dartlang.org/flutter_osm_plugin-0.29.1+3/ios/Classes/Extension.swift: 225: 37: error: binary operator'-'
    cannot be applied to operands of type'Double' and'CGFloat'
            let size = CGPoint (x: width-(rect.minX --rect.maxX), y: height-(rect.minY --rect.maxY))

⇒let size = CGPoint (x: CGFloat (width)-(rect.minX --rect.maxX), y: CGFloat (height)-(rect.minY --rect.maxY))

~~/development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_osm_plugin-0.29.1+3/ios/Classes/MyMapView.swift:782:100: error: cannot convert value of
    type 'CGFloat' to expected argument type 'Double'
                let bounding = mapView.getBounds(width: mainView.bounds.width, height: mainView.bounds.height)

⇒let bounding = mapView.getBounds(width: Double(mainView.bounds.width), height: Double(mainView.bounds.height))


Is this the cause?

**Comment by liodali** [comment]
ok i will fix that

**Comment by liodali** [comment]
if you're working on mac, you can overcome the problem temporary by open you project on XCode 
and in Pods folder try to find MyMapView.swift inside of flutter_osm_plugin folder
and switch this line 
```swift
let bounding = mapView.getBounds(width: mainView.bounds.width, height: mainView.bounds.height)
```
to
```swift
let bounding = mapView.getBounds(width: Double(mainView.bounds.width), height: Double(mainView.bounds.height))
``` 
rebuild the project

**Comment by mor7348** [comment]
thank you. 
I will try it.

**Comment by mor7348** [comment]
I get an error in two places, and if I change it as follows, no error appears.

let size = CGPoint (x: width-(rect.minX --rect.maxX), y: height-(rect.minY --rect.maxY))
⇒let size = CGPoint (x: CGFloat (width)-(rect.minX --rect.maxX), y: CGFloat (height)-(rect.minY --rect.maxY))

let bounding = mapView.getBounds(width: mainView.bounds.width, height: mainView.bounds.height)
⇒let bounding = mapView.getBounds(width: Double(mainView.bounds.width), height: Double(mainView.bounds.height))

However, the map has been blacked out.

Flutter 2.8.1
Dart 2.15.1
Xcode 12.5.1

Thank you.

**Comment by liodali** [comment]
when you do that, the map return working normally or you face another problem ?

**Comment by mor7348** [comment]
The problem hasn't changed.
The controller is working and it seems that only the map part is not displayed.

controller.setMarkerIcon
controller.centerMap
controller.removeMarker
etc ...
These are working.

**Comment by mor7348** [comment]
![Simulator Screen Shot - iPhone 11 Pro Max - 2022-02-08 at 11 06 15](https://user-images.githubusercontent.com/38882637/152905414-222cff2e-aad8-4867-8294-d585e94a3423.png)

**Comment by liodali** [comment]
Sorry for the late reply,
I want you to open your project with XCode and  search in pods folder for flutter_osm_plugin try to find the file MyMapView
and uncommend the lines 98 and 99 and comment the lines 100 and 100
and after that run your application and told me if the map shows or not

**Comment by liodali** [comment]
i think the problem is related to style file that i'm using to customize the map and render the raster tile 
because that sdk can render vector tile also.
so i need to make style file can be reach over the internet and  maybe  theengine faced a problem to access to it because i using shared file in dropbox :disappointed_relieved: 

try to return it back like it was before the changes and told me it return black screen or still working

**Comment by mor7348** [comment]
I commented out and uncommented back.
After all, the map will be blacked out.

![image_iphone](https://user-images.githubusercontent.com/38882637/153692033-18286f08-72ea-4dd7-8cda-c108969322af.png)

**Comment by liodali** [comment]
keep the way where the map is working 
i will find another solution for raster tile 
i will published in next version

**Comment by mor7348** [comment]
Thank you very much. waiting for the next version.

**Comment by mor7348** [comment]
Sorry for too late reply.
I have connected and debugged the actual iPhone, but the map does not show up. (IOS15.2)
I don't know about appetize as I have never tried it, but I will try it.

Since I can't confirm the display on IOS, I had been developing on Android. (Run on Android emulator)

The app shuts down as shown below, do you know why? (This situation happened suddenly)

----
I/OsmDroid( 4338): Using tile source: Mapnik
I/OsmDroid( 4338): Tile cache increased from 0 to 9
E/osm     ( 4338): osm flutter plugin create
E/osm     ( 4338): osm flutter plugin start
E/osm     ( 4338): osm flutter plugin resume
E/BufferQueueProducer( 4338): [SurfaceTexture-0-4338-1](id:10f200000001,api:1,p:364,c:4338) dequeueBuffer: BufferQueue has been abandoned
E/AndroidRuntime( 4338): FATAL EXCEPTION: main
E/AndroidRuntime( 4338): Process: com.---.app PID: 4338
E/AndroidRuntime( 4338): java.lang.NullPointerException: Attempt to invoke virtual method 'org.osmdroid.views.MapViewRepository org.osmdroid.views.MapView.getRepository()' on a null object reference
E/AndroidRuntime( 4338): 	at org.osmdroid.views.overlay.infowindow.InfoWindow.<init>(InfoWindow.java:53)
E/AndroidRuntime( 4338): 	at org.osmdroid.views.overlay.infowindow.BasicInfoWindow.<init>(BasicInfoWindow.java:54)
E/AndroidRuntime( 4338): 	at org.osmdroid.views.overlay.infowindow.MarkerInfoWindow.<init>(MarkerInfoWindow.java:41)
E/AndroidRuntime( 4338): 	at org.osmdroid.views.MapViewRepository.getDefaultMarkerInfoWindow(MapViewRepository.java:55)
E/AndroidRuntime( 4338): 	at org.osmdroid.views.overlay.Marker.<init>(Marker.java:116)
E/AndroidRuntime( 4338): 	at org.osmdroid.views.overlay.Marker.<init>(Marker.java:93)
E/AndroidRuntime( 4338): 	at hamza.dali.flutter_osm_plugin.models.FlutterMarker.<init>(FlutterMaker.kt:24)
E/AndroidRuntime( 4338): 	at hamza.dali.flutter_osm_plugin.models.FlutterMarker.<init>(FlutterMaker.kt:60)
E/AndroidRuntime( 4338): 	at hamza.dali.flutter_osm_plugin.FlutterOsmView.createMarker(FlutterOsmView.kt:805)
E/AndroidRuntime( 4338): 	at hamza.dali.flutter_osm_plugin.FlutterOsmView.createMarker$default(FlutterOsmView.kt:804)
E/AndroidRuntime( 4338): 	at hamza.dali.flutter_osm_plugin.FlutterOsmView.addMarker(FlutterOsmView.kt:736)
E/AndroidRuntime( 4338): 	at hamza.dali.flutter_osm_plugin.FlutterOsmView.addMarker$default(FlutterOsmView.kt:731)
E/AndroidRuntime( 4338): 	at hamza.dali.flutter_osm_plugin.FlutterOsmView$setCacheMap$1$invokeSuspend$$inlined$forEach$lambda$1.invokeSuspend(FlutterOsmView.kt:587)
E/AndroidRuntime( 4338): 	at hamza.dali.flutter_osm_plugin.FlutterOsmView$setCacheMap$1$invokeSuspend$$inlined$forEach$lambda$1.invoke(Unknown Source:10)
E/AndroidRuntime( 4338): 	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
E/AndroidRuntime( 4338): 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:165)
E/AndroidRuntime( 4338): 	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
E/AndroidRuntime( 4338): 	at hamza.dali.flutter_osm_plugin.FlutterOsmView$setCacheMap$1.invokeSuspend(FlutterOsmView.kt:586)
E/AndroidRuntime( 4338): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
E/AndroidRuntime( 4338): 	at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:377)
E/AndroidRuntime( 4338): 	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:30)
E/AndroidRuntime( 4338): 	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:25)
E/AndroidRuntime( 4338): 	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:110)
E/AndroidRuntime( 4338): 	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
E/AndroidRuntime( 4338): 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
E/AndroidRuntime( 4338): 	at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1)
E/AndroidRuntime( 4338): 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
E/AndroidRuntime( 4338): 	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:1)
E/AndroidRuntime( 4338): 	at hamza.dali.flutter_osm_plugin.FlutterOsmView.setCacheMap(FlutterOsmView.kt:582)
E/AndroidRuntime( 4338): 	at hamza.dali.flutter_osm_plugin.FlutterOsmView.onMethodCall(FlutterOsmView.kt:329)
E/AndroidRuntime( 4338): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/AndroidRuntime( 4338): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:178)
E/AndroidRuntime( 4338): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$handleMessageFromDart$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:206)
E/AndroidRuntime( 4338): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/AndroidRuntime( 4338): 	at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime( 4338): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 4338): 	at android.os.Looper.loop(Looper.java:223)
E/AndroidRuntime( 4338): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/AndroidRuntime( 4338): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 4338): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/AndroidRuntime( 4338): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
I/Process ( 4338): Sending signal. PID: 4338 SIG: 9
Lost connection to device.

**Comment by mor7348** [comment]
Connected iphone (IOS15.2), the emulator showed the map.
I haven't figured out why yet, but I'm glad anyway. I'm going to proceed with the development.

**Comment by liodali** [comment]
what is the version that you're using ? and can you share small sample to understand you use case more 
and i will try to look deep into the log

**Comment by jesussmile** [comment]
Hey I have the same problem running on iOS version 13.7 on an iPad. the screen is blacked out. Do I still need to uncomment the lines as you have described above ? seems to work fine in newer version of iOS above 14. however it did work the first time, now it keeps giving black screen.

**Comment by jesussmile** [comment]
```ruby
// let sceneUpdates = [TGSceneUpdate]()
             let sceneUpdates = [TGSceneUpdate(path: "global.sdk_api_key", value: "qJz9K05vRu6u_tK8H3LmzQ")]
             let sceneUrl = URL(string: "https://www.nextzen.org/carto/bubble-wrap-style/9/bubble-wrap-style.zip")!
            //let sceneUrl = URL(string: //"https://dl.dropboxusercontent.com/s/25jzvtghx0ac2rk/osm-style.zip?dl=0")!
            mapView.loadSceneAsync(from: sceneUrl, with: sceneUpdates)
```
Anyways uncommenting and commenting helped. by the way How can it now shows a better map style with 3D buildings, how can I enable this in android ?

**Comment by liodali** [comment]
in android using another sdk
but im planning to add that also for android
and for blackscreen because style file maybe not downloaded 
maybe dropbix blocking access 
i will check it and i will try to fix that for all sorry for that

**Comment by liodali** [comment]
try the ney version now, i changed the location of styles

**Comment by AlehSabadashGmail** [comment]
Hey @liodali issue is persist, version  0.40.3
just black screen with icons, I am using this [example](https://github.com/liodali/osm_flutter/blob/master/example/lib/src/home/home_example.dart)
