### ISSUE TITLE
NullPointerException when killing the application

### ISSUE THREAD

**Issue by Eimji** [liodali/osm_flutter#267]
Hello

There is an issue after killing the application:
```
D/OsmDroid(29387): Unable to create base path at null
D/OsmDroid(29387): java.lang.NullPointerException: Attempt to invoke virtual method 'java.io.File android.content.Context.getExternalFilesDir(java.lang.String)' on a null object reference
D/OsmDroid(29387): 	at org.osmdroid.config.DefaultConfigurationProvider.getOsmdroidBasePath(DefaultConfigurationProvider.java:264)
D/OsmDroid(29387): 	at org.osmdroid.config.DefaultConfigurationProvider.getOsmdroidTileCache(DefaultConfigurationProvider.java:293)
D/OsmDroid(29387): 	at org.osmdroid.config.DefaultConfigurationProvider.getOsmdroidTileCache(DefaultConfigurationProvider.java:287)
D/OsmDroid(29387): 	at hamza.dali.flutter_osm_plugin.FlutterOsmPlugin.onDetachedFromActivity(FlutterOsmPlugin.kt:123)
D/OsmDroid(29387): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.detachFromActivity(FlutterEngineConnectionRegistry.java:383)
D/OsmDroid(29387): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onDetach(FlutterActivityAndFragmentDelegate.java:681)
D/OsmDroid(29387): 	at io.flutter.embedding.android.FlutterActivity.onDestroy(FlutterActivity.java:715)
D/OsmDroid(29387): 	at android.app.Activity.performDestroy(Activity.java:8322)
D/OsmDroid(29387): 	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1376)
D/OsmDroid(29387): 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5441)
D/OsmDroid(29387): 	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5487)
D/OsmDroid(29387): 	at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:47)
D/OsmDroid(29387): 	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
D/OsmDroid(29387): 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
D/OsmDroid(29387): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
D/OsmDroid(29387): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2253)
D/OsmDroid(29387): 	at android.os.Handler.dispatchMessage(Handler.java:106)
D/OsmDroid(29387): 	at android.os.Looper.loopOnce(Looper.java:201)
D/OsmDroid(29387): 	at android.os.Looper.loop(Looper.java:288)
D/OsmDroid(29387): 	at android.app.ActivityThread.main(ActivityThread.java:7870)
D/OsmDroid(29387): 	at java.lang.reflect.Method.invoke(Native Method)
D/OsmDroid(29387): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
D/OsmDroid(29387): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

Could you have a look please?

**Comment by liodali** [comment]
i will check it  and i will fix that

**Comment by liodali** [comment]
check the new version `0.34.1`

**Comment by Eimji** [comment]
Great !!! It works now ! The bug has been fixed. Thanks.
