### ISSUE TITLE
The app crash when i use image_picker package 

### ISSUE THREAD

**Issue by h1amza** [liodali/osm_flutter#325]
E/osm     (23337): osm flutter plugin pause
E/osm     (23337): osm flutter plugin pause
E/osm     (23337): osm flutter plugin stopped
D/AndroidRuntime(23337): Shutting down VM
E/AndroidRuntime(23337): FATAL EXCEPTION: main
E/AndroidRuntime(23337): Process: com.jolitaxi.jolitaxichauffeur, PID: 23337
E/AndroidRuntime(23337): java.lang.RuntimeException: Unable to stop activity {com.jolitaxi.jolitaxichauffeur/com.joli.taxi_driver.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void org.osmdroid.api.IMapController.stopAnimation(boolean)' on a null object reference
E/AndroidRuntime(23337): 	at android.app.ActivityThread.callActivityOnStop(ActivityThread.java:4858)
E/AndroidRuntime(23337): 	at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:4829)
E/AndroidRuntime(23337): 	at android.app.ActivityThread.handleStopActivity(ActivityThread.java:4903)
E/AndroidRuntime(23337): 	at android.app.servertransaction.StopActivityItem.execute(StopActivityItem.java:40)
E/AndroidRuntime(23337): 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
E/AndroidRuntime(23337): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
E/AndroidRuntime(23337): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
E/AndroidRuntime(23337): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(23337): 	at android.os.Looper.loop(Looper.java:223)
E/AndroidRuntime(23337): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/AndroidRuntime(23337): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(23337): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/AndroidRuntime(23337): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/AndroidRuntime(23337): Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void org.osmdroid.api.IMapController.stopAnimation(boolean)' on a null object reference
E/AndroidRuntime(23337): 	at org.osmdroid.views.overlay.mylocation.MyLocationNewOverlay.disableFollowLocation(MyLocationNewOverlay.java:408)
E/AndroidRuntime(23337): 	at hamza.dali.flutter_osm_plugin.overlays.CustomLocationManager.disableFollowAndLocation(CustomLocation.kt:35)
E/AndroidRuntime(23337): 	at hamza.dali.flutter_osm_plugin.overlays.CustomLocationManager.onStopLocation(CustomLocation.kt:40)
E/AndroidRuntime(23337): 	at hamza.dali.flutter_osm_plugin.FlutterOsmView.onStop(FlutterOsmView.kt:2061)
E/AndroidRuntime(23337): 	at androidx.lifecycle.FullLifecycleObserverAdapter.onStateChanged(FullLifecycleObserverAdapter.java:48)
E/AndroidRuntime(23337): 	at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:354)
E/AndroidRuntime(23337): 	at androidx.lifecycle.LifecycleRegistry.backwardPass(LifecycleRegistry.java:284)
E/AndroidRuntime(23337): 	at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:302)
E/AndroidRuntime(23337): 	at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:148)
E/AndroidRuntime(23337): 	at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:134)
E/AndroidRuntime(23337): 	at androidx.lifecycle.ReportFragment.dispatch(ReportFragment.java:68)
E/AndroidRuntime(23337): 	at androidx.lifecycle.ReportFragment$LifecycleCallbacks.onActivityPreStopped(ReportFragment.java:210)
E/AndroidRuntime(23337): 	at android.app.Activity.dispatchActivityPreStopped(Activity.java:1433)
E/AndroidRuntime(23337): 	at android.app.Activity.performStop(Activity.java:8194)
E/AndroidRuntime(23337): 	at android.app.ActivityThread.callActivityOnStop(ActivityThread.java:4850)
E/AndroidRuntime(23337): 	... 12 more
I/Process (23337): Sending signal. PID: 23337 SIG: 9
Lost connection to device.

**Comment by liodali** [comment]
you need provide how you're using picker with the map

**Comment by h1amza** [comment]
so i have a home page where i have osm map and a button to go to test widget:

`
import 'dart:io';

import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';

class TestWidget extends StatefulWidget {
  const TestWidget({Key? key}) : super(key: key);

  @override
  State<TestWidget> createState() => _TestWidgetState();
}

class _TestWidgetState extends State<TestWidget> {
  File? cameraFile;
  File? galleryFile;
  final ImagePicker _picker = ImagePicker();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          if (cameraFile != null) Expanded(child: Image.file(cameraFile!)),
          const SizedBox(height: 10),
          if (galleryFile != null) Expanded(child: Image.file(galleryFile!)),
        ],
      ),
      floatingActionButton: Column(
        mainAxisAlignment: MainAxisAlignment.end,
        children: [
          IconButton(
            onPressed: () async {
              final XFile? photo = await _picker.pickImage(
                source: ImageSource.camera,
                maxHeight: 500,
                maxWidth: 500,
                imageQuality: 85,
              );
              if (photo != null) cameraFile = File(photo.path);
              setState(() {});
            },
            icon: const Icon(Icons.camera_alt_outlined),
          ),
          const SizedBox(height: 20),
          IconButton(
            onPressed: () async {
              final XFile? photo = await _picker.pickImage(
                source: ImageSource.gallery,
                maxHeight: 500,
                maxWidth: 500,
                imageQuality: 85,
              );
              if (photo != null) galleryFile = File(photo.path);
              setState(() {});
            },
            icon: const Icon(Icons.photo_library_rounded),
          ),
        ],
      ),
    );
  }
}
`

**Comment by h1amza** [comment]
when i use only test widget as a home page it's work but when the osm map is my home page the app crash

**Comment by liodali** [comment]
it's crash when you try to open the test page from home page 
not when the app open ?

**Comment by h1amza** [comment]
when i press to IconButton for camera or galley select and give me the first logs

**Comment by liodali** [comment]
can you provide  me the code of that button

**Comment by h1amza** [comment]
it's in the test widget: https://github.com/liodali/osm_flutter/issues/325#issuecomment-1220998834

`
IconButton(
            onPressed: () async {
              final XFile? photo = await _picker.pickImage(
                source: ImageSource.camera,
                maxHeight: 500,
                maxWidth: 500,
                imageQuality: 85,
              );
              if (photo != null) cameraFile = File(photo.path);
              setState(() {});
            },
            icon: const Icon(Icons.camera_alt_outlined),
          ),
`

**Comment by h1amza** [comment]
when i set  trackMyPosition to true and i call myLocation and go to test widget and try to picke un image  the app crash

**Comment by liodali** [comment]
don't use setState with map 
replace cameraFile Type to ValueNotifier<File?> and use ValueListenableBuilder to show the image 
if the map has no relation with camera picker 
extract that part in seperate widget

**Comment by h1amza** [comment]
the following code : https://github.com/liodali/osm_flutter/issues/325#issuecomment-1220998834 is in seperate widget as i told you and setState it's not the problem because the app crash in this line:
`
final XFile? photo = await _picker.pickImage( source: ImageSource.camera, maxHeight: 500, maxWidth: 500, imageQuality: 85, );
`

**Comment by h1amza** [comment]
i create a repo (the same code in your example folder): https://github.com/h1amza/test_osm_flutter
and i add the test widget (with ValueNotifier) just run the code and click on mylocation button first then to gallery botton

**Comment by liodali** [comment]
ok i will check thanks

**Comment by liodali** [comment]
for now if you want try to make built in camera in your app
i need to make more investigation why the restard when app go to background and back again

**Comment by h1amza** [comment]
is there a function to stop or pause the map?

**Comment by liodali** [comment]
thats done automatically inside the plugin
and in flutter we dont have the same lifecycle in android 
try to use camera package instead of the picker

**Comment by h1amza** [comment]
i need access to gallery to that's why i use image_picker

**Comment by liodali** [comment]
use this package https://pub.dev/packages/photo_gallery
to make built in gallery also 
sorry for that i dont know why it behave like that
i tested that use case(make app go to background and back to forground  ane it didnt behave like open another app i will checked why

**Comment by h1amza** [comment]
ok i will see

**Comment by h1amza** [comment]
there is any update about this issue?

**Comment by liodali** [comment]
technicaly I found a solution but I have wierd behaviour I need to fixed and make some test to publish the solution

**Comment by h1amza** [comment]
ok thanks for letting me know

**Comment by wlan07** [comment]
hello there ,
I'm coming to open an issue here , but I found it already opened 
the crash actually happens directly after the app goes for the background like when you tap on system home button or you launch another app from the flutter app

**Comment by liodali** [comment]
it wierd i testedthat case 
the problem here that when you open other applicaton from current like @h1amza  did open camera app
force the map to rebuild 
can you provide me more information about what you did and log error also if it possible

**Comment by liodali** [comment]
i have small solution that you can disable location when you open new page or that page that will open camera app 
and when you return the map page re-activate again the track location

**Comment by liodali** [comment]
I will publish new version contain fix for this issue today

**Comment by liodali** [comment]
but take care that when openning a new page or remove the page that contain map with tracking activate should be disabled 
because no need to keep the location activate  
for now I added disable the user location when map disposed or go to background

**Comment by liodali** [comment]
check the new version `0.40.1`
