### ISSUE TITLE
custom map don't work

### ISSUE THREAD

**Issue by hansmboron** [liodali/osm_flutter#335]
Only the default map worked correctly for me, the other maps are giving error.
in flutter_osm_plugin version: ^0.37.2+5 everything is working, in newer versions it doesn't work

this works
```dart
mapController = MapController(
  areaLimit: bb,
  initMapWithUserPosition: true,
);
```

this don't
```dart
mapController = MapController.publicTransportationLayer(
  areaLimit: bb,
  initMapWithUserPosition: true,
);

mapController = MapController.cyclOSMLayer(
  areaLimit: bb,
  initMapWithUserPosition: true,
);

mapController = MapController.customLayer(
  initMapWithUserPosition: true,
  areaLimit: bb,
  customTile: CustomTile(
    sourceName: "opentopomap",
    tileExtension: ".png",
    minZoomLevel: 2,
    maxZoomLevel: 19,
    urlsServers: [
      TileURLs(
        url: "https://{s}.tile.opentopomap.org/",
        subdomains: ['a', 'b', 'c'],
      )
    ],
    tileSize: 256,
  ),
);
```

error
```
E/MethodChannel#flutter/platform_views(32072): java.lang.ArrayStoreException: source[0] of type java.util.ArrayList cannot be stored in destination array of type java.lang.String[]
E/MethodChannel#flutter/platform_views(32072): 	at java.lang.System.arraycopy(Native Method)
E/MethodChannel#flutter/platform_views(32072): 	at java.util.Arrays.copyOf(Arrays.java:3647)
E/MethodChannel#flutter/platform_views(32072): 	at java.util.ArrayList.toArray(ArrayList.java:421)
E/MethodChannel#flutter/platform_views(32072): 	at hamza.dali.flutter_osm_plugin.FlutterOsmView.initMap(FlutterOsmView.kt:2170)
E/MethodChannel#flutter/platform_views(32072): 	at hamza.dali.flutter_osm_plugin.FlutterOsmView.onCreate(FlutterOsmView.kt:1997)
E/MethodChannel#flutter/platform_views(32072): 	at androidx.lifecycle.FullLifecycleObserverAdapter.onStateChanged(FullLifecycleObserverAdapter.java:36)
E/MethodChannel#flutter/platform_views(32072): 	at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:354)
E/MethodChannel#flutter/platform_views(32072): 	at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.java:196)
E/MethodChannel#flutter/platform_views(32072): 	at hamza.dali.flutter_osm_plugin.FlutterOsmView.<init>(FlutterOsmView.kt:266)
E/MethodChannel#flutter/platform_views(32072): 	at hamza.dali.flutter_osm_plugin.OsmFactory.create(OsmFactory.kt:31)
E/MethodChannel#flutter/platform_views(32072): 	at io.flutter.plugin.platform.PlatformViewsController$1.createForTextureLayer(PlatformViewsController.java:230)
E/MethodChannel#flutter/platform_views(32072): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:122)
E/MethodChannel#flutter/platform_views(32072): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:60)
E/MethodChannel#flutter/platform_views(32072): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/MethodChannel#flutter/platform_views(32072): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/MethodChannel#flutter/platform_views(32072): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/MethodChannel#flutter/platform_views(32072): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MethodChannel#flutter/platform_views(32072): 	at android.os.Handler.handleCallback(Handler.java:938)
E/MethodChannel#flutter/platform_views(32072): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#flutter/platform_views(32072): 	at android.os.Looper.loopOnce(Looper.java:226)
E/MethodChannel#flutter/platform_views(32072): 	at android.os.Looper.loop(Looper.java:313)
E/MethodChannel#flutter/platform_views(32072): 	at android.app.ActivityThread.main(ActivityThread.java:8751)
E/MethodChannel#flutter/platform_views(32072): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter/platform_views(32072): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
E/MethodChannel#flutter/platform_views(32072): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
E/flutter (32072): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(error, source[0] of type java.util.ArrayList cannot be stored in destination array of type java.lang.String[], null, java.lang.ArrayStoreException: source[0] of type java.util.ArrayList cannot be stored in destination array of type java.lang.String[]
E/flutter (32072): 	at java.lang.System.arraycopy(Native Method)
E/flutter (32072): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:60)
E/flutter (32072): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/flutter (32072): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/flutter (32072): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/flutter (32072): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/flutter (32072): 	at android.os.Handler.handleCallback(Handler.java:938)
E/flutter (32072): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/flutter (32072): 	at android.os.Looper.loopOnce(Looper.java:226)
E/flutter (32072): 	at android.os.Looper.loop(Looper.java:313)
E/flutter (32072): 	at android.app.ActivityThread.main(ActivityThread.java:8751)
E/flutter (32072): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (32072): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
E/flutter (32072): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
E/flutter (32072): )
E/flutter (32072): #0      StandardMethodCodec.decodeEnvelope
package:flutter/…/services/message_codecs.dart:653
E/flutter (32072): #1      MethodChannel._invokeMethod
package:flutter/…/services/platform_channel.dart:296
E/flutter (32072): <asynchronous suspension>
E/flutter (32072): #2      TextureAndroidViewController._sendCreateMessage
package:flutter/…/services/platform_views.dart:1146
E/flutter (32072): <asynchronous suspension>
E/flutter (32072): #3      AndroidViewController.create
package:flutter/…/services/platform_views.dart:792
E/flutter (32072): <asynchronous suspension>
E/flutter (32072): #4      AndroidViewController.setSize
package:flutter/…/services/platform_views.dart:819
E/flutter (32072): <asynchronous suspension>
E/flutter (32072): #5      RenderAndroidView._sizePlatformView
package:flutter/…/rendering/platform_view.dart:182
E/flutter (32072): <asynchronous suspension>
E/flutter (32072):


```

**Comment by liodali** [comment]
thnx i will fix this error , I will publish new version
