### ISSUE TITLE
roadWidth is int and can't cast to double

### ISSUE THREAD

**Issue by tabooo** [liodali/osm_flutter#409]
flutter_osm_plugin: ^0.53.4+1

```
await mapController.drawMultipleRoad(
      configs,
      commonRoadOption: const MultiRoadOption(
        roadColor: Colors.red,
      ),
    );
```

```
E/flutter ( 8227): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(404, java.lang.Integer cannot be cast to java.lang.Double, java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Double
E/flutter ( 8227): 	at hamza.dali.flutter_osm_plugin.models.RoadConfigKt.toRoadOption(RoadConfig.kt:30)
E/flutter ( 8227): 	at hamza.dali.flutter_osm_plugin.FlutterOsmView.drawMultiRoad(FlutterOsmView.kt:1386)
E/flutter ( 8227): 	at hamza.dali.flutter_osm_plugin.FlutterOsmView.onMethodCall(FlutterOsmView.kt:462)
E/flutter ( 8227): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
E/flutter ( 8227): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/flutter ( 8227): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/flutter ( 8227): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/flutter ( 8227): 	at android.os.Handler.handleCallback(Handler.java:938)
E/flutter ( 8227): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/flutter ( 8227): 	at android.os.Looper.loop(Looper.java:223)
E/flutter ( 8227): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/flutter ( 8227): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter ( 8227): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/flutter ( 8227): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/flutter ( 8227): , null)
E/flutter ( 8227): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:652:7)
E/flutter ( 8227): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:310:18)
E/flutter ( 8227): <asynchronous suspension>
E/flutter ( 8227): #2      MethodChannel.invokeListMethod (package:flutter/src/services/platform_channel.dart:496:35)
E/flutter ( 8227): <asynchronous suspension>
E/flutter ( 8227): #3      MethodChannelOSM.drawMultipleRoad (package:flutter_osm_interface/src/channel/osm_method_channel.dart:664:10)
E/flutter ( 8227): <asynchronous suspension>
E/flutter ( 8227): #4      MobileOSMController.drawMultipleRoad (package:flutter_osm_plugin/src/controller/osm/osm_controller.dart:752:12)
E/flutter ( 8227): <asynchronous suspension>
E/flutter ( 8227): #5      MapController.drawMultipleRoad (package:flutter_osm_plugin/src/controller/map_controller.dart:380:12)
E/flutter ( 8227): <asynchronous suspension>
E/flutter ( 8227): #6      _MyHomePageState.drawMultiRoads (package:video_control/pages/home.dart:110:5)
```

![image](https://github.com/liodali/osm_flutter/assets/787425/9037ca19-5506-45a2-bfb4-b211af985d71)

**Comment by liodali** [comment]
oh will fix that

**Comment by liodali** [comment]
check the new version 0.54.0
