### ISSUE TITLE
MarkerIcon don't display on iOS

### ISSUE THREAD

**Issue by Gael-Tonnellier** [liodali/osm_flutter#447]
Hi, 
I'm using this plugins since december 2023 and I 'm running into a bug on version 0.42.

I display some static geopoint on a map , it works very well on Android but sometimes on iOS, icon don't display . The marker's position is good  but icon not . I try with severals icons ( Icons and CupertinoIcons ) the bug is still the same . 

![Simulator Screenshot - iPhone 14 Pro - 2023-08-28 at 14 34 38](https://github.com/liodali/osm_flutter/assets/77383473/7223871e-0f3b-4ea2-b8c7-b03bfa71ddaf)

My code : 

```
StaticPositionGeoPoint(
                                  dechet['id'].toString(), 
                                   MarkerIcon(icon: Icon(CupertinoIcons.location_solid)),
                                  [
                                GeoPoint(
                                    latitude: dechet['geolocalisation'][0],
                                    longitude: dechet['geolocalisation'][1])
                              ])
```

I know I'm far from the latest version but for the moment it's hard for us to update all plugins version. 

If you have a clue of how to solve it ;)

 Thank you

**Comment by Gael-Tonnellier** [comment]
hmm I saw Icon appears good at first call but if I leave the map and come back :  that error appears

**Comment by liodali** [comment]
for now I don't have clear answer for this issue and why it happen in ios side
it will try to do more investigation about it

**Comment by liodali** [comment]
can you provide me code sample of how your icons looks like ?

**Comment by Gael-Tonnellier** [comment]
`import 'package:flutter_osm_plugin/flutter_osm_plugin.dart';

import '../backend/api_requests/api_calls.dart';
import '../components/map_details_widget.dart';
import '../flutter_flow/flutter_flow_google_map.dart';
import '../flutter_flow/flutter_flow_icon_button.dart';
import '../flutter_flow/flutter_flow_theme.dart';
import '../flutter_flow/flutter_flow_util.dart';
import '../flutter_flow/custom_functions.dart' as functions;
import 'package:flutter/material.dart';
import 'package:font_awesome_flutter/font_awesome_flutter.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:provider/provider.dart';

class DechetsDechetterieListWidget extends StatefulWidget {
  const DechetsDechetterieListWidget({Key? key}) : super(key: key);

  @override
  _DechetsDechetterieListWidgetState createState() =>
      _DechetsDechetterieListWidgetState();
}

class _DechetsDechetterieListWidgetState
    extends State<DechetsDechetterieListWidget> {
  final _unfocusNode = FocusNode();
  final scaffoldKey = GlobalKey<ScaffoldState>();
  MapController mapController = MapController(
    initMapWithUserPosition: false,
    initPosition:
        GeoPoint(latitude: 48.9225381971337, longitude: 6.635435401703112),
    areaLimit: BoundingBox(
      east: 10.4922941,
      north: 47.8084648,
      south: 45.817995,
      west: 5.9559113,
    ),
  );

  @override
  void dispose() {
    _unfocusNode.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    context.watch<FFAppState>();
    return Scaffold(
      key: scaffoldKey,
      resizeToAvoidBottomInset: false,
      backgroundColor: FlutterFlowTheme.of(context).primaryBackground,
      appBar: AppBar(
        backgroundColor: FlutterFlowTheme.of(context).primaryColor,
        automaticallyImplyLeading: false,
        leading: FlutterFlowIconButton(
          borderColor: Colors.transparent,
          borderRadius: 30,
          borderWidth: 1,
          buttonSize: 60,
          icon: Icon(
            Icons.arrow_back_rounded,
            color: Colors.white,
            size: 30,
          ),
          onPressed: () async {
            context.pop();
          },
        ),
        title: Text(
          FFLocalizations.of(context).getText(
            'kj6uus21' /* Choix de la déchetterie */,
          ),
          style: FlutterFlowTheme.of(context).subtitle1.override(
                fontFamily: 'Helvetica',
                color: FlutterFlowTheme.of(context).primaryBackground,
                useGoogleFonts: false,
              ),
        ),
        actions: [],
        centerTitle: false,
        elevation: 2,
      ),
      body: SafeArea(
        child: GestureDetector(
          onTap: () => FocusScope.of(context).requestFocus(_unfocusNode),
          child: FutureBuilder<ApiCallResponse>(
            future: DechetDechetterieCall.call(),
            builder: (context, snapshot) {
              // Customize what your widget looks like when it's loading.
              if (!snapshot.hasData) {
                return Center(
                  child: SizedBox(
                    width: 50,
                    height: 50,
                    child: CircularProgressIndicator(
                      color: FlutterFlowTheme.of(context).primaryColor,
                    ),
                  ),
                );
              }
              final dechetsDechetterieListDechetDechetterieResponse =
                  snapshot.data!;
              List<StaticPositionGeoPoint> listeDechets =
                  List<StaticPositionGeoPoint>.from(
                      dechetsDechetterieListDechetDechetterieResponse.jsonBody
                          .map((dechet) => StaticPositionGeoPoint(
                                  dechet['id'].toString(), MarkerIcon(icon: Icon(CupertinoIcons.location_solid)), [
                                GeoPoint(
                                    latitude: dechet['geolocalisation'][0],
                                    longitude: dechet['geolocalisation'][1])
                              ])));

              return Column(
                mainAxisSize: MainAxisSize.max,
                children: [
                  Expanded(
                    child: DefaultTabController(
                      length: 2,
                      initialIndex: 0,
                      child: Column(
                        children: [
                          TabBar(
                            labelColor:
                                FlutterFlowTheme.of(context).primaryText,
                            labelStyle:
                                FlutterFlowTheme.of(context).bodyText1.override(
                                      fontFamily: 'Poppins',
                                      letterSpacing: -0.02,
                                    ),
                            indicatorColor:
                                FlutterFlowTheme.of(context).primaryText,
                            tabs: [
                              Tab(
                                text: FFLocalizations.of(context).getText(
                                  'fchv9qjb' /* Toutes */,
                                ),
                              ),
                              Tab(
                                text: FFLocalizations.of(context).getText(
                                  'kan9ipz5' /* Carte */,
                                ),
                              ),
                            ],
                          ),
                          Expanded(
                            child: TabBarView(
                              physics: NeverScrollableScrollPhysics(),
                              children: [
                                Builder(
                                  builder: (context) {
                                    final dechetItem = getJsonField(
                                      dechetsDechetterieListDechetDechetterieResponse
                                          .jsonBody,
                                      r'''$''',
                                    ).toList();
                                    return ListView.builder(
                                      padding: EdgeInsets.zero,
                                      scrollDirection: Axis.vertical,
                                      itemCount: dechetItem.length,
                                      itemBuilder: (context, dechetItemIndex) {
                                        final dechetItemItem =
                                            dechetItem[dechetItemIndex];
                                        return InkWell(
                                          onTap: () async {
                                            context.pushNamed(
                                              'dechets_dechetterie_info',
                                              queryParams: {
                                                'dechetInfo': serializeParam(
                                                  getJsonField(
                                                    dechetItemItem,
                                                    r'''$''',
                                                  ),
                                                  ParamType.JSON,
                                                ),
                                              }.withoutNulls,
                                            );
                                          },
                                          child: Column(
                                            mainAxisSize: MainAxisSize.max,
                                            crossAxisAlignment:
                                                CrossAxisAlignment.center,
                                            children: [
                                              ListTile(
                                                leading: FaIcon(
                                                  FontAwesomeIcons.trashAlt,
                                                  color: FlutterFlowTheme.of(
                                                          context)
                                                      .primaryText,
                                                ),
                                                title: Text(
                                                  getJsonField(
                                                    dechetItemItem,
                                                    r'''$.nom''',
                                                  ).toString(),
                                                  textAlign: TextAlign.start,
                                                  style: FlutterFlowTheme.of(
                                                          context)
                                                      .title3
                                                      .override(
                                                        fontFamily: 'Poppins',
                                                        fontSize: 14,
                                                      ),
                                                ),
                                                trailing: Icon(
                                                  Icons.arrow_forward_ios,
                                                  color: Color(0xFF303030),
                                                  size: 14,
                                                ),
                                                tileColor: Color(0xFFF5F5F5),
                                                dense: false,
                                              ),
                                              Divider(
                                                height: 1,
                                                thickness: 2,
                                                indent: 20,
                                                endIndent: 20,
                                                color: Color(0xFFD9D9D9),
                                              ),
                                            ],
                                          ),
                                        );
                                      },
                                    );
                                  },
                                ),
                                Stack(
                                  alignment: AlignmentDirectional(0, 0),
                                  children: [
                                    Align(
                                      alignment: AlignmentDirectional(0, 0),
                                      child: OSMFlutter(
                                        mapIsLoading: Center(
                                          child: CircularProgressIndicator(),
                                        ),
                                        controller: mapController,
                                        trackMyPosition: false,
                                        initZoom: 10,
                                        minZoomLevel: 8,
                                        maxZoomLevel: 18,
                                        stepZoom: 1.0,
                                        staticPoints: listeDechets,
                                        onGeoPointClicked: (geopoint) {
                                          Map<String, dynamic> dechetterie =
                                              dechetsDechetterieListDechetDechetterieResponse
                                                  .jsonBody
                                                  .firstWhere(
                                                      (dechet) =>
                                                          GeoPoint(
                                                              latitude: dechet[
                                                                      "geolocalisation"]
                                                                  [0],
                                                              longitude: dechet[
                                                                      "geolocalisation"]
                                                                  [1]) ==
                                                          geopoint,
                                                      orElse: () => null);

                                          showModalBottomSheet<void>(
                                            isScrollControlled: true,
                                            backgroundColor: Colors.transparent,
                                            context: context,
                                            builder: (context) {
                                              return Padding(
                                                padding: MediaQuery.of(context)
                                                    .viewInsets,
                                                child: Container(
                                                  height: 200,
                                                  child: MapDetailsWidget(
                                                    markInfo: dechetterie,
                                                  ),
                                                ),
                                              );
                                            },
                                          );
                                        },
                                      ),
                                    ),
                                    Align(
                                      alignment: AlignmentDirectional(0, -1),
                                      child: Container(
                                        width: double.infinity,
                                        height: 30,
                                        decoration: BoxDecoration(
                                          color: Color(0xFFD9D9D9),
                                        ),
                                        child: Row(
                                          mainAxisSize: MainAxisSize.max,
                                          crossAxisAlignment:
                                              CrossAxisAlignment.start,
                                          children: [
                                            Padding(
                                              padding: EdgeInsetsDirectional
                                                  .fromSTEB(20, 7, 0, 0),
                                              child: Text(
                                                valueOrDefault<String>(
                                                  functions
                                                      .getLength(getJsonField(
                                                    dechetsDechetterieListDechetDechetterieResponse
                                                        .jsonBody,
                                                    r'''$''',
                                                  )),
                                                  '0',
                                                ),
                                                style:
                                                    FlutterFlowTheme.of(context)
                                                        .bodyText1
                                                        .override(
                                                          fontFamily: 'Poppins',
                                                          fontWeight:
                                                              FontWeight.bold,
                                                        ),
                                              ),
                                            ),
                                            Padding(
                                              padding: EdgeInsetsDirectional
                                                  .fromSTEB(5, 7, 0, 0),
                                              child: Text(
                                                FFLocalizations.of(context)
                                                    .getText(
                                                  'vahx7mbj' /* résultats */,
                                                ),
                                                style:
                                                    FlutterFlowTheme.of(context)
                                                        .bodyText1
                                                        .override(
                                                          fontFamily: 'Poppins',
                                                          fontWeight:
                                                              FontWeight.bold,
                                                        ),
                                              ),
                                            ),
                                          ],
                                        ),
                                      ),
                                    ),
                                    Align(
                                      alignment: AlignmentDirectional(0, -0.9),
                                      child: Container(
                                        width:
                                            MediaQuery.of(context).size.width *
                                                0.9,
                                        height:
                                            MediaQuery.of(context).size.height *
                                                0.65,
                                        constraints: BoxConstraints(
                                          maxHeight: 65,
                                        ),
                                        decoration: BoxDecoration(
                                          color: Color(0xFF393A4B),
                                          borderRadius:
                                              BorderRadius.circular(3),
                                          shape: BoxShape.rectangle,
                                        ),
                                        child: Row(
                                          mainAxisSize: MainAxisSize.min,
                                          mainAxisAlignment:
                                              MainAxisAlignment.center,
                                          children: [
                                            Text(
                                              FFLocalizations.of(context)
                                                  .getText(
                                                'qt6kuv8j' /* Sélectionnez la déchetterie su... */,
                                              ),
                                              textAlign: TextAlign.center,
                                              style:
                                                  FlutterFlowTheme.of(context)
                                                      .bodyText1
                                                      .override(
                                                        fontFamily: 'Poppins',
                                                        color: Colors.white,
                                                        fontSize: 14,
                                                        letterSpacing: 0.02,
                                                        fontWeight:
                                                            FontWeight.w200,
                                                      ),
                                            ),
                                          ],
                                        ),
                                      ),
                                    ),
                                  ],
                                ),
                              ],
                            ),
                          ),
                        ],
                      ),
                    ),
                  ),
                ],
              );
            },
          ),
        ),
      ),
    );
  }
}
`

**Comment by liodali** [comment]
another point you can improve your code to make widget load smooth 
by make `dechetsDechetterieListDechetDechetterieResponse` in initState and when it's ready you can use this apis 

```dart
 await controller.setMarkerOfStaticPoint(
      id: id,
      markerIcon:  icon,
    );

    await controller.setStaticPosition(
     dechetsDechetterieList,
      id,
    );


```
with this way you can show the map and later statics will be shown later

**Comment by liodali** [comment]
Another note I'm thinking to change how we set statics marker
where it's better to use GeoJson for those type of markers

**Comment by Gael-Tonnellier** [comment]
> when the icons shows in that way did the map reload or not ? just I want to know also the flutter version used ? because maybe I need to make cache system to the ios side for markers

Yes the map is reload. Flutter version is 3.7.3.

**Comment by liodali** [comment]
ok thnx I think I need to add cache system for iOS side also
I will let you know soon when that part will be ready

**Comment by xyzbilal** [comment]
this error produced while trying to add marker. 
```

[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: 'package:flutter/src/rendering/proxy_box.dart': Failed assertion: line 3379 pos 12: '!debugNeedsPaint': is not true.
proxy_box.dart:3379
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
#2      RenderRepaintBoundary.toImage
proxy_box.dart:3379
#3      MethodChannelOSM._capturePng
osm_method_channel.dart:327
#4      MethodChannelOSM.addMarker
osm_method_channel.dart:537
#5      MobileOSMController.addMarker.<anonymous closure>
osm_controller.dart:472
#6      new Future.delayed.<anonymous closure> (dart:async/future.dart:427:39)
#7      Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
#8      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
#9      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
#10     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189:12)

```

I just add widget as a static point. 
```

 Positioned.fill(
            child: OSMFlutter(
              controller: c.mapController!,
              mapIsLoading:
                  Center(child: CircularProgressIndicator(color: bcekmeceGreen))
                      .sized(50, 50),
              onMapIsReady: (v) {
                print("ready");
              },
              osmOption: OSMOption(
                staticPoints: [
                  StaticPositionGeoPoint(
                      "u",
                      MarkerIcon(
                        iconWidget: circle(size: 30),
                      ),
                      [c.location.value!])
                ],
                zoomOption: ZoomOption(initZoom: 17),
              ),
            ),
          )
```

**Comment by jaisinghdhande** [comment]
Hi @liodali @Gael-Tonnellier , any update on the bug fix? Facing the same issue for ios.

**Comment by liodali** [comment]
the issue from the inner sdk
im trying to do some fixes

**Comment by jaisinghdhande** [comment]
Okay, also is it possible for me to know the tentative time for this fix because i have a huge dependency regarding this feature. Or even a temporary fix for this.

**Comment by liodali** [comment]
good news we will change our ios sdk and we hope that this bug will dispear forever 
the new sdk will be in next version which 1.0.0 because we will have the same feature in all the platform

**Comment by liodali** [comment]
we update our ios sdk check our latest dev version : `1.0.0-dev.1`

**Comment by jaisinghdhande** [comment]
Thankyou for the help and support. Will check the new version soon.
